# Custom Language File for Launcher Customizer

[ejs.app]
title = "ValoLands Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/ODGTV/ValoLands-V2"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/bPJJAsFxrj"

[ejs.settings]
sourceGithubLink = "https://github.com/ODGTV/ValoLands-V2"
supportLink = "https://github.com/ODGTV/ValoLands-V2/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR VALOLANDS !"
welcomeDescription = "Notre mission est de créer un des meilleurs serveurs PVP Faction de France. Grâce à la collaboration des Fondateurs, du développeur et de la communauté, nous avons cherché à créer ValoLands V2. Alors, on espère vous voir sur ValoLands !"
welcomeDescCTA = "Vous n'êtes qu'à quelques clics de ValoLands."